{{- if .Values.ingress.enabled -}}
{{- $fullName := include "gitlabautodevops.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "gitlabautodevops.name" . }}
    helm.sh/chart: {{ include "gitlabautodevops.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  tls:
  - hosts:
      - {{ template "hostname" .Values.service.url }}
    secretName: {{ $fullName }}-tls
  rules:
    - host: {{ template "hostname" .Values.service.url }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ .Values.service.externalPort }}
{{- end }}
